---
categories:
- blog post
date: 08/11/2024
format:
  html:
    df-print: paged
    toc: true
text:
title: Top 10 must watch Movies

---
Here are the list of top 5 movies that is a must watch

# List of top 5 movies

## 1.The Godfather

**Director: Francis Ford Coppola**

Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son, Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.

## 2. Inception

**Director: Christopher Nolan**

A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.

## 3.Pulp Fiction

**Director: Quentin Tarantino**

The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.

## 4.Interstellar

**Director: Christopher Nolan**

When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.

## 5.Avengers: Infinity War

**Director: Russo Brothers**

The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.

